### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchFieldError: DebugMode         at me.exzork.gcauth.GCAuth.lambda$onEnable$1(GCAuth.java:94)         at io.javalin.core.JavalinConfig.applyUserConfig(JavalinConfig.java:205)         at io.javalin.Javalin.create(Javalin.java:89)         at express.Express.<init>(Express.java:39)         at me.exzork.gcauth.GCAuth.onEnable(GCAuth.java:50)         at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$2(PluginManager.java:116)         at java.base/java.util.HashMap.forEach(HashMap.java:1420)         at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:114)         at emu.grasscutter.Grasscutter.main(Grasscutter.java:100)

### ISSUE THREAD

**Issue by sht547** [exzork/GCAuth#1]
Exception in thread "main" java.lang.NoSuchFieldError: DebugMode
        at me.exzork.gcauth.GCAuth.lambda$onEnable$1(GCAuth.java:94)
        at io.javalin.core.JavalinConfig.applyUserConfig(JavalinConfig.java:205)
        at io.javalin.Javalin.create(Javalin.java:89)
        at express.Express.<init>(Express.java:39)
        at me.exzork.gcauth.GCAuth.onEnable(GCAuth.java:50)
        at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$2(PluginManager.java:116)
        at java.base/java.util.HashMap.forEach(HashMap.java:1420)
        at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:114)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:100)

**Comment by exzork** [comment]
I'll look into it later today,
Can you give me more information such as which branch are you using and
last commit?

**Comment by exzork** [comment]
Fixed in the latest release
